CREATE TABLE users (
  user_id SMALLINT UNSIGNED AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL,
  display_name VARCHAR(500),
  avatar_path VARCHAR(1000),
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
);
