// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Auth struct {
	AuthID       sql.NullInt16
	UserID       uint16
	SessionToken sql.NullString
	CsrfToken    sql.NullString
	PasswordHash sql.NullString
	CreatedAt    time.Time
}

type User struct {
	UserID      sql.NullInt16
	Email       string
	DisplayName sql.NullString
	AvatarPath  sql.NullString
	Password    string
	CreatedAt   time.Time
}
